title: 'animevictory.github.io'
description: ":v"
baseurl: ""
url: "https://animevictory.github.io"

header_pages:
  - about.md
  - peter.md
  - contact.md

style: light 

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-seo-tag



permalink: /:year/:month/:day/:title:output_ext